"""Graph state definitions and structured Pydantic schemas.

This module defines the shared multi-agent state dictionary and structured
data contracts for routing decisions and analysis reports.
"""

from typing import Annotated, Sequence, TypedDict, Literal
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


class RouterOutput(BaseModel):
    """Structured routing decision emitted by the Lead Analyst Supervisor."""

    next_node: Literal["code_analyst", "doc_parser", "FINISH"] = Field(
        description="Next worker agent to invoke, or 'FINISH' if user intent is met."
    )
    reasoning: str = Field(
        description="Justification for the chosen route based on conversation context."
    )


class AnalysisReport(BaseModel):
    """Structured report returned for code audits or technical document queries."""

    summary: str = Field(
        description="High-level overview of analysis findings and context."
    )
    critical_issues: list[str] = Field(
        default_factory=list,
        description="Security vulnerabilities, syntax bugs, or specification violations identified.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable optimizations, architectural refactoring, or remediation steps.",
    )


class AgentState(TypedDict):
    """Shared execution state passed across nodes in the LangGraph workflow.

    Attributes:
        messages: The sequence of messages representing the conversation history,
            accumulated via LangGraph's `add_messages` reducer.
        next_node: The next destination node decided by the supervisor.
        target_file: Optional path to a source code file targeted for audit.
        report: Optional structured analysis report generated by worker agents.
    """

    messages: Annotated[Sequence[BaseMessage], add_messages]
    next_node: str
    target_file: str | None
    report: AnalysisReport | None
